/**
 * Regenerates src/lib/pdf/org-name-kn.generated.ts — the PDF letterhead's
 * Kannada org name as pre-shaped vector outlines.
 *
 *   npx tsx scripts/build-org-name-kn.mts
 *
 * Why not plain <Text>: the name is spelt ಫೋಟೋಗ್ರಾಫರ‍್ಸ್, with a ZWJ
 * (ರ + ZWJ + ್ + ಸ) so ರ stays a full letter with ಸ as its ottu, the way
 * MDPVA writes it — rather than the default arkavattu form ಫರ್ಸ್.
 * Browsers' shaper (HarfBuzz) honours that ZWJ, but react-pdf's (fontkit)
 * doesn't: it draws a dotted-circle placeholder instead. So the name is
 * shaped here with HarfBuzz itself, against the same font file the PDF
 * embeds, and the PDF draws the resulting glyph outlines as an <Svg>.
 *
 * Re-run after changing ORG.nameKn — application-pdf.test.ts fails until
 * the generated text matches it.
 */
import fs from "node:fs";
import path from "node:path";

import * as hb from "harfbuzzjs";

import { ORG } from "../src/lib/onboarding/i18n";

const FONT = path.join(process.cwd(), "src/assets/fonts/NotoSansKannada-Bold.ttf");
const OUT = path.join(process.cwd(), "src/lib/pdf/org-name-kn.generated.ts");

const fontData = fs.readFileSync(FONT);
const face = new hb.Face(new hb.Blob(fontData.buffer.slice(
  fontData.byteOffset,
  fontData.byteOffset + fontData.byteLength,
)));
const font = new hb.Font(face);

function shape(text: string) {
  const buffer = new hb.Buffer();
  buffer.addText(text);
  buffer.guessSegmentProperties();
  hb.shape(font, buffer);
  return buffer;
}

const buffer = shape(ORG.nameKn);
const dottedCircle = shape("\u25CC").getGlyphInfos()[0].codepoint;

const { ascender, descender } = font.hExtents();
const height = ascender - descender;

/** glyphToPath gives absolute M/L/Q/C/Z commands in font units, y-up; move
 * each glyph to its pen position and flip to the SVG/PDF y-down space. */
function place(d: string, dx: number, dy: number): string {
  return d.replace(/([MLQCZ])([^MLQCZ]*)/g, (_, cmd: string, args: string) => {
    const nums = args.split(/[\s,]+/).filter(Boolean).map(Number);
    const out: string[] = [];
    for (let i = 0; i < nums.length; i += 2) {
      out.push(`${Math.round(nums[i] + dx)} ${Math.round(ascender - (nums[i + 1] + dy))}`);
    }
    return cmd + out.join(" ");
  });
}

let penX = 0;
let penY = 0;
const parts: string[] = [];
const positions = buffer.getGlyphPositions();
buffer.getGlyphInfos().forEach((info, i) => {
  const pos = positions[i];
  // HarfBuzz falls back to a dotted circle, or .notdef (glyph 0), when a
  // sequence can't shape — fail loudly instead of baking that in.
  if (info.codepoint === 0 || info.codepoint === dottedCircle) {
    throw new Error(`Unshapeable sequence at character ${info.cluster} of ORG.nameKn`);
  }
  parts.push(place(font.glyphToPath(info.codepoint), penX + pos.xOffset, penY + pos.yOffset));
  penX += pos.xAdvance;
  penY += pos.yAdvance;
});

const source = `// GENERATED by scripts/build-org-name-kn.mts — do not edit by hand.
// ORG.nameKn shaped with HarfBuzz in NotoSansKannada-Bold.ttf; units are
// font units (${face.upem}/em), y-down, origin at the ascender line.

export const ORG_NAME_KN_OUTLINE = {
  text: ${JSON.stringify(ORG.nameKn).replace(/\u200D/g, "\\u200D")},
  upem: ${face.upem},
  width: ${penX},
  height: ${height},
  d: ${JSON.stringify(parts.join(""))},
} as const;
`;

fs.writeFileSync(OUT, source);
console.log(`Wrote ${path.relative(process.cwd(), OUT)} (${penX}×${height} units)`);
